name: Workflow Evento
on:
  push:
    branches: ["feature/*"]
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
    - name: Action de Teste
      run: echo "Action apenas executada na main e feature"