name: Workflow Event
on:
  push:
jobs:
  apenas-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Esses Jobs sรณ executam na branch main
    runs-on: ubuntu-latest
    steps:
      - name: Executando na main
        run: echo "Executando comando na main"