name: Workflow Event Control
on:
  push:
jobs:
  exemplo-fluxo-execucao-01:
    runs-on: ubuntu-latest
    steps:
      - name: Vai falhar
        run: l
  exemplo-fluxo-execucao-02:
    runs-on: ubuntu-latest
    needs: [exemplo-fluxo-execucao-01]
    if: ${{ failure() }}
    steps:
      - name: Execução com sucesso
        run: echo "Execução com sucesso"
  apenas-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Esses Jobs só executam na branch main
    runs-on: ubuntu-latest
    steps:
      - name: Executando na main
        run: echo "Executando comando na main"
  bora:
    runs-on: ubuntu-latest
    steps:
      - name: Execução em feature
        if: ${{ contains(github.ref,'refs/heads/feature') }}
        run: echo "Execução em Feature"
      - name: Envio de Erros
        if: ${{ failure() }}
        run: echo "Envio de erro"