name: Workflow Event Control
on:
  push:
jobs:
  apenas-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Esses Jobs só executam na branch main
    runs-on: ubuntu-latest
    steps:
      - name: Executando na main
        run: echo "Executando comando na main"
  bora:
    runs-on: ubuntu-latest
    steps:
        if: ${{ contains(github.ref,'refs/heads/feature') }}
      - name: Execução em feature
        run: echo "Execução em Feature"